version: "3"

networks:
  laravel:

services:
  webService:
    image: nginx:stable-alpine
    container_name: nginx
    ports:
      - "8080:80"
    volumes:
      - ./api-1:/var/www/1/
      - ./api-2:/var/www/2/
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - api-1
      - api-2
      - database
    networks:
      - laravel

  database:
    image: mysql:5.7.22
    container_name: database
    restart: unless-stopped
    tty: true
    ports:
      - "3306:3306"
    volumes:
      - ./mysql:/var/lib/mysql
    environment:
      MYSQL_DATABASE: systgo
      MYSQL_USER: vmpradob
      MYSQL_PASSWORD: pass
      MYSQL_ROOT_PASSWORD: pass_root
      SERVICE_TAG: dev
      SERVICE_NAME: mysql

    networks:
      - laravel

  api-1:
    build:
      context: ./api-1
      dockerfile: Dockerfile
    container_name: api-1
    volumes:
      - ./api-1:/var/www/1/
    ports:
      - "9000:9000"
    networks:
      - laravel
  api-2:
    build:
      context: ./api-2
      dockerfile: Dockerfile
    container_name: api-2
    volumes:
      - ./api-2:/var/www/2/
    ports:
      - "9001:9000"
    networks:
      - laravel
  client:
    build: 
      context: ./client
      dockerfile: Dockerfile
    container_name: client
    tty: true
    volumes:
      - ./client:/var/www/html
    ports:
      - "3000:3000"
    networks:
      - laravel